FROM node:20.19.5-alpine3.22 AS build

WORKDIR /app

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27.5-alpine

COPY --from=build --chown=nginx:nginx /app/dist /usr/share/nginx/html

EXPOSE 8080
USER nginx
